# Project 1
## Collect Data

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
import pandas as pd
mdf = pd.read_csv('linked_mortality_file_1999_2000.csv') # Load mortality file
print( mdf.head() )
gdf = pd.read_sas("DEMO.xpt", format="xport") # Load demographics file
print( gdf.head() )
df = gdf.merge(mdf, on="SEQN", how="inner") # Merge mortality and demographics on SEQN variable

   SEQN  ELIGSTAT  MORTSTAT  UCOD_LEADING  DIABETES  HYPERTEN  PERMTH_INT  \
0     1         2       NaN           NaN       NaN       NaN         NaN
1     2         1       1.0           6.0       0.0       0.0       177.0
2     3         2       NaN           NaN       NaN       NaN         NaN
3     4         2       NaN           NaN       NaN       NaN         NaN
4     5         1       0.0           NaN       NaN       NaN       244.0

   PERMTH_EXM
0         NaN
1       177.0
2         NaN
3         NaN
4       244.0
   SEQN  SDDSRVYR  RIDSTATR  RIDEXMON  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDAGEEX  \
0   1.0       1.0       2.0       2.0       2.0       2.0      29.0      31.0
1   2.0       1.0       2.0       2.0       1.0      77.0     926.0     926.0
2   3.0       1.0       2.0       1.0       2.0      10.0     125.0     126.0
3   4.0       1.0       2.0       2.0       1.0       1.0      22.0      23.0
4   5.0       1.0       2.0       2.0       1.0      49.0     597.0     597.0

   RIDRETH1  RIDRETH2  ...      WTIREP43      WTIREP44      WTIREP45  \
0       4.0       2.0  ...  10094.017100   9912.461855   9727.078709
1       3.0       1.0  ...  27186.728682  27324.345051  28099.663528
2       3.0       1.0  ...  43993.193099  44075.386428  46642.563799
3       4.0       2.0  ...  10702.307249  10531.444441  10346.119327
4       3.0       1.0  ...  93164.782430  92119.608772  95388.490406

       WTIREP46      WTIREP47      WTIREP48      WTIREP49      WTIREP50  \
0  10041.524113  9.953956e+03   9857.381983   9865.152486  10327.992682
1  27757.066921  2.804929e+04  26716.602006  26877.704909  27268.025234
2  44967.681579  4.457248e+04  44087.945688  44831.370881  44480.987235
3  10636.063039  5.397605e-79  10533.108939  10654.749584  10851.024385
4  94131.383538  9.529781e+04  91325.082461  91640.586117  92817.926915

       WTIREP51      WTIREP52
0   9809.165049  10323.315747
1  27406.383620  26984.812909
2  45389.112766  43781.905637
3  10564.981435  11012.529729
4  94282.855382  91993.251203

[5 rows x 144 columns]

In [64]:
sdf=pd.read_sas("SMQ.xpt", format="xport")
sdf.head()

,SEQN,SMQ020,SMD030,SMQ040,SMQ050Q,SMQ050U,SMD055,SMD057,SMD070,SMD075,...,SMQ180,SMD190,SMQ200,SMD203,SMQ205,SMQ210,SMD220,SMQ230,SMD233,SMD235
0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
1,5.0,1.0,5.397605e-79,3.0,5.0,3.0,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,1.0,5.397605e-79,NaN,NaN,NaN
2,7.0,1.0,1.700000e+01,3.0,20.0,4.0,39.0,20.0,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
3,10.0,1.0,1.600000e+01,1.0,NaN,NaN,NaN,NaN,10.0,25.0,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
4,12.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN

In [67]:
new_df=pd.merge(df, sdf, on="SEQN", how="inner")
df.head()

,SEQN,SMQ020,SMD030,SMQ040,SMQ050Q,SMQ050U,SMD055,SMD057,SMD070,SMD075,...,SMQ180,SMD190,SMQ200,SMD203,SMQ205,SMQ210,SMD220,SMQ230,SMD233,SMD235
0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
1,5.0,1.0,5.397605e-79,3.0,5.0,3.0,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,1.0,5.397605e-79,NaN,NaN,NaN
2,7.0,1.0,1.700000e+01,3.0,20.0,4.0,39.0,20.0,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
3,10.0,1.0,1.600000e+01,1.0,NaN,NaN,NaN,NaN,10.0,25.0,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
4,12.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN